# Configuração Nixpacks para Railway
# Adiciona dependências necessárias para WPPConnect/Puppeteer

[phases.setup]
nixPkgs = [
  'nodejs_18',
  'chromium',
  'nss',
  'freetype',
  'harfbuzz',
  'ca-certificates',
  'ttf-freefont',
  'fontconfig',
  'libxshmfence',
  'libgbm',
  'glib',
  'gtk3',
  'pango',
  'cairo',
  'alsa-lib',
  'libdrm',
  'mesa',
  'xorg.libX11',
  'xorg.libXcomposite',
  'xorg.libXdamage',
  'xorg.libXext',
  'xorg.libXfixes',
  'xorg.libXrandr',
  'cups',
  'expat',
  'dbus',
  'at-spi2-core',
  'at-spi2-atk'
]

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
